/*
 * @Date: 2022-01-27 17:12:59
 * @LastEditors: zhaozc
 * @LastEditTime: 2022-02-08 14:56:29
 * @FilePath: \ruipeng-ui\examples\components\theme\constant.js
 */
export const DEFAULT_THEME_CONFIG = {
    global: {},
    local: {}
}

export const RUIPENG_THEME_USER_CONFIG = 'RUIPENG_THEME_USER_CONFIG'

export const RUIPENG_THEME_PREVIEW_CONFIG = 'RUIPENG_THEME_PREVIEW_CONFIG'

export const ACTION_DOWNLOAD_THEME = 'RUIPENG_THEME_ACTION_DOWNLOAD'

export const ACTION_APPLY_THEME = 'RUIPENG_THEME_ACTION_ALLPY_CSS'

export const ACTION_COMPONECT_SELECT = 'RUIPENG_THEME_ACTION_COMPONECT_SELECT'

export const ACTION_USER_CONFIG_UPDATE = 'RUIPENG_THEME_USER_CONFIG_UPDATE'
